"""empty message

Revision ID: f6b541285a78
Revises: 2616c79fd05b
Create Date: 2024-11-09 03:18:21.362869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b541285a78'
down_revision = '2616c79fd05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint(None, ['profile_pic'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
